### ISSUE TITLE
v1.2.4 causing AttributeErrors

### ISSUE THREAD

**Issue by goodspark** [tox-dev/sphinx-autodoc-typehints#31] opened 2018-01-17 19:38 UTC
```
AttributeError: module 'my.module' has no attribute 'accept.<locals>'
```

Does not occur in v1.2.3

It appears to happen whenever I use [hypothesis] in a test class.

```python
from hypothesis import given, integers


class TestSomething:
  @given(seconds=integers(min_value=1, max_value=100))
  def test_something(self, seconds: int):
    pass


# does not repro if no test class is used
@given(seconds=integers(min_value=1, max_value=100))
def test_something_else(seconds: int):
  pass
```

[hypothesis]: http://hypothesis.readthedocs.io/

<details>
<summary>Sphinx log output</summary>

```
# Sphinx version: 1.6.5
# Python version: 3.6.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 19%] ref/tests.plugin.pyramid
#   
#   reading sources... [ 20%] ref/tests.plugin.settings_fixtures
#   
#   reading sources... [ 21%] ref/tests.project
#   
#   reading sources... [ 22%] ref/tests.project.models
#   
#   reading sources... [ 24%] ref/tests.project.models.test_project
#   
# Loaded extensions:
#   alabaster (0.7.10) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.5) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.intersphinx (1.6.5) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (1.6.5) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.extlinks (1.6.5) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/extlinks.py
#   sphinx_autodoc_typehints (unknown version) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx_autodoc_typehints.py
#   ghlink (unknown version) from /home/my/code/project/docs/_extensions/ghlink.py
#   sphinx.ext.graphviz (1.6.5) from /home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/graphviz.py
Traceback (most recent call last):
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in update
    self._read_serial(docnames, self.app)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 603, in _read_serial
    self.read_doc(docname, app)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 726, in read_doc
    pub.publish()
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1833, in run
    documenter.generate(more_content=self.content)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1133, in generate
    self.document_members(all_members)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1054, in document_members
    check_module=members_check_module and not isattr)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1133, in generate
    self.document_members(all_members)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1530, in document_members
    ModuleLevelDocumenter.document_members(self, all_members)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1054, in document_members
    check_module=members_check_module and not isattr)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1120, in generate
    sig = self.format_signature()
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 1326, in format_signature
    return Documenter.format_signature(self)  # type: ignore
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 759, in format_signature
    self.object, self.options, args, retann)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/application.py", line 493, in emit_firstresult
    return self.events.emit_firstresult(event, self, *args)
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/events.py", line 84, in emit_firstresult
    for result in self.emit(name, *args):
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/my/code/project/.tox/docs/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 130, in process_signature
    cls = getattr(module, clsname)
AttributeError: module 'tests.project.models.test_project' has no attribute 'accept.<locals>'
```
</details>

**Comment by agronholm** [comment] 2018-01-17 20:00
Any idea where the `accept.<locals>` is coming from? Will this code alone repro the problem?

**Comment by agronholm** [comment] 2018-01-17 20:00
Also, if you remove the decorator, does it fix the problem?

**Comment by agronholm** [comment] 2018-02-13 07:09
27 days and no response – closing.

**Comment by akaihola** [comment] 2018-08-09 21:40
I had a similar problem with a decorator, and I managed to reduce it to this:
```python
class BaseClass:
    @staticmethod
    def dummy_method_decorator(method):
        def wrapper(self) -> str:
            return method(self)

        return wrapper


class ChildClass(BaseClass):
    @BaseClass.dummy_method_decorator
    def f(self):
        return 'a string'
```
```python
Exception occurred:
  File "/sphinx_autodoc_typehints.py", line 135, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'function' object has no attribute '<locals>'
```
The problem occurs because `wrapper()` has a return value annotation (`-> str`). Take that off, and there's no error.

In the debugger, I see:
```python
  File "/home/kaiant/.virtualenvs/enipy2016-py36/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 135, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'function' object has no attribute '<locals>'
> sphinx_autodoc_typehints.py(135)process_signature()
-> outer = getattr(outer, clsname)
(Pdb) obj
<function BaseClass.dummy_method_decorator.<locals>.wrapper at 0x7fbc808e39d8>
```

This is sphinx-autodoc-typehints 1.3.0.

**Comment by goodspark** [comment] 2018-10-27 06:17
@agronholm Can we reopen this and have another look?

**Comment by agronholm** [comment] 2018-10-28 19:06
@goodspark When decorating functions/methods, it is customary to use `@functools.wraps` on it. That should also fix your problem. Have you tried it?

**Comment by goodspark** [comment] 2018-10-28 23:39
I see. It seems this might be an issue with how hypothesis is wrapping the functions. I'll follow up there. Thanks!

**Comment by ikelos** [comment] 2018-11-13 11:53
It might be worth documenting this somewhere, for those that don't use the custom of wrapping functions with `@functools.wraps`.  A line in the readme would likely be enough...  5:)

**Comment by ikelos** [comment] 2018-12-16 22:31
@agronholm, `@functools.wraps` is handy when directly wrapping a function, but I'm trying essentially to use a wrapper to proxy the call somewhere else.  The code is along the lines of:

```
def get_method_wrapper(method: str) -> Callable:

    def wrapper(self, name: str) -> Callable:
        return getattr(self.proxy, method)(self.name + name)

    return wrapper

newthing.proxied = get_method_wrapper("proxied")
```
It's not trivial to wrap, because I can't get `self` until the wrapper's been called, so annotating it with the method in question can't happen because it's dependent upon the object it's assigned to.  It would be extremely handy if sphinx-autodoc-typehints could either handle such a situation, or not fail with an exception.

Even something like the following patch, would at least fail gracefully and allow the rest of the documentation to be built, rather than aborting the whole process due to the exception.  It might be better to check for `clsname[0] == '<'` in order to catch any other unusual setups, but I don't know in what other circumstances this might occur?

[naive-introspection.patch.txt](https://github.com/agronholm/sphinx-autodoc-typehints/files/2684023/naive-introspection.patch.txt)

**Comment by joernweissenborn** [comment] 2019-01-21 21:13
I stumbled over the same issue today. 

The problem lies in the attribute `__module__` of your wrapped method. If you do a `print(get_method_wrapper("proxied"))` you will see an output like
 something.get_method_wrapper.<locals>

The  wrapper is declared as part of the local variables of the `get_method_wrapper` function. The trouble is when inspecting the class, it gets a hickup at the `<locals>` part, since its not a 'normal' attribute.

You can hopefully fix your code by replacing the `__module__` of your attribute with the ones from you class like this, for me it worked at least.

    def get_method_wrapper(method: str) -> Callable:

        def wrapper(self, name: str) -> Callable:
            newfun = getattr(self.proxy, method)(self.name + name)
            newfun.__module__ = self.proxy.__module__
            return newfun
        return wrapper

You might also need to adapt `__name__` and `__qualname__`.

**Comment by ikelos** [comment] 2019-01-21 22:15
Hiya @joernweissenborn, thanks for the suggestion!

Unfortunately, it's not the response of the wrapper that needs its `__qualname__` changing, it's the wrapper itself, which unfortunately doesn't have a self to be bound to yet.  It did however set me on a different path, so adding the lines:

```
def get_module_wrapper(method: str) -> Callable:

    def wrapper(self, name: str) -> Callable:
        return getattr(self.proxy, method)(self.name + name)

    for entry in ['__annotations__', '__doc__', '__module__', '__name__', '__qualname__']:
        proxy_interface = getattr(InterfaceForProxyClass, method)
        if hasattr(proxy_interface, entry):
            setattr(wrapper, entry, getattr(proxy_interface, entry))

    return wrapper
```
just before return `wrapper`, succeeded in allowing the documentation to complete.  This is the closest I can get to duplicating the values from the inherited class (as indicated by `InterfaceForProxyClass`), but it seems to cover the main elements we care about for the documentation (`__doc__` and `__annotations__`).  Thanks for the pointer, it's a shame this kind of situation can't be resolved within the autodoc-typehint code itself, but at least we've got a documented resolution...  5:)

**Comment by joernweissenborn** [comment] 2019-01-21 23:56
I think that `wraps` basically does the same thing in a more complete way. It just relies on a function prototype. In my case, I don't have it, since I add methods to a class with a decorator. 

I don't now much about inspecting `<locals>`, but I think `sphinx-autodoc-typehints` should throw at least a  kind of custom `LocalMethodException` when it encounters these kind of situations it cannot deal with it to help indentify this problems when you have class factories.

**Comment by gaborbernat** [comment] 2022-01-08 11:34
Please check again with latest release and report back if the problem is still active.

**Closed by gaborbernat** 2022-01-08 11:34 UTC
Labels: invalid
